name: 'Malcontent PR Diff Analyzer'
description: 'Run malcontent on PR diffs to analyze security changes between versions'
author: 'Jason'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  base-ref:
    description: 'Base ref to compare against (defaults to PR base branch)'
    required: false
  head-ref:
    description: 'Head ref to analyze (defaults to PR head branch)'
    required: false
  malcontent-version:
    description: 'Version of malcontent to use (defaults to latest)'
    required: false
    default: 'latest'
  fail-on-increase:
    description: 'Fail the action if risk score increases'
    required: false
    default: 'true'
  comment-on-pr:
    description: 'Comment results on the PR'
    required: false
    default: 'true'
  base-path:
    description: 'Base path within the repository to run malcontent (defaults to repository root)'
    required: false
    default: '.'
  mode:
    description: 'Mode to run malcontent in: "diff" (default) or "analyze"'
    required: false
    default: 'diff'

outputs:
  diff-summary:
    description: 'Summary of malcontent findings diff'
  risk-increased:
    description: 'Whether the risk score increased'
  report-file:
    description: 'Path to the full diff report'

runs:
  using: 'node20'
  main: 'dist/index.js'