name: Dependabot auto-merge

on: pull_request

permissions: {}

jobs:
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to enable auto-merge on the PR
      pull-requests: write # Required to mark the PR for auto-merge
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Enable auto-merge for Dependabot PRs
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
