name: Malcontent Analysis

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  malcontent:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write # Required for PR comments

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0  # Fetch all history for proper diff analysis

      - name: Run Malcontent Analysis
        id: malcontent
        uses: ./ # In actual usage, this would be: chainguard-dev/malcontent-action@...
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # NB: Could also set `fail-on-increase: false` and use `if: ${{steps.malcontent.outputs.risk-delta > 5}}` to allow some risk increase

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        if: always() # Upload even if the malcontent check fails
        with:
          sarif_file: ${{ steps.malcontent.outputs.sarif-file }}
          category: malcontent
